//> using scala 3.8.1
//> using dep com.lihaoyi::ujson:4.4.3
//> using dep com.lihaoyi::os-lib:0.11.8

// Generated by Claude Sonnet 4.6

/** Compares two directories of per-platform JVM index files and produces a Markdown summary of
  * added entries.
  *
  * Usage: scala-cli summarize-index-changes.scala -- <base-indices-dir> <pr-indices-dir>
  *
  * Each directory contains files named <os>-<arch>.json with the structure: { "<jvm-name>": {
  * "<version>": "<url>", ... }, ... }
  */
object SummarizeIndexChanges:

  def longestCommonPrefix(strings: Seq[String]): String =
    if strings.isEmpty then ""
    else
      strings.reduce: (a, b) =>
        a.zip(b).takeWhile((x, y) => x == y).map(_._1).mkString

  def readIndex(file: os.Path): Map[String, Map[String, String]] =
    if os.exists(file) then
      ujson
        .read(os.read(file))
        .obj
        .view
        .mapValues(_.obj.view.mapValues(_.str).toMap)
        .toMap
    else
      Map.empty

  def main(args: Array[String]): Unit =
    if args.length != 2 then
      System.err.println("Usage: summarize-index-changes.scala <base-indices-dir> <pr-indices-dir>")
      sys.exit(1)

    val baseDir = os.Path(args(0), os.pwd)
    val prDir   = os.Path(args(1), os.pwd)

    val preferredOrder = Seq(
      "linux-arm64.json",
      "linux-amd64.json",
      "darwin-arm64.json",
      "darwin-amd64.json",
      "windows-arm64.json",
      "windows-amd64.json",
      "linux-musl-arm64.json",
      "linux-musl-amd64.json"
    )

    val allFiles =
      (
        (if os.exists(baseDir) then os.list(baseDir) else Seq.empty) ++
          (if os.exists(prDir) then os.list(prDir) else Seq.empty)
      )
        .map(_.last)
        .filter(_.endsWith(".json"))
        .distinct
        .sortWith: (a, b) =>
          val ai = preferredOrder.indexOf(a)
          val bi = preferredOrder.indexOf(b)
          if ai >= 0 && bi >= 0 then ai < bi
          else if ai >= 0 then true
          else if bi >= 0 then false
          else a < b

    val sb         = new StringBuilder
    var hasChanges = false

    for file <- allFiles do
      val osArch  = file.stripSuffix(".json")
      val baseMap = readIndex(baseDir / file)
      val prMap   = readIndex(prDir / file)

      val allJvms = (baseMap.keySet ++ prMap.keySet).toSeq.sorted

      // Collect (displayName, urls) pairs, stripping -java<N> suffixes
      val jvmAddedUrls = allJvms.flatMap: jvm =>
        val baseVersions  = baseMap.getOrElse(jvm, Map.empty)
        val prVersions    = prMap.getOrElse(jvm, Map.empty)
        val addedVersions = prVersions.filter((k, _) => !baseVersions.contains(k))
        if addedVersions.isEmpty then None
        else
          val urls       = addedVersions.values.toSeq.map(url => url.dropWhile(_ != '+').drop(1))
          val displayJvm = jvm.replaceAll("-java\\d+$", "")
          Some((displayJvm, urls))

      // Merge entries sharing the same display name, preserving first-occurrence order
      val jvmChanges = jvmAddedUrls
        .foldLeft(Vector.empty[(String, Seq[String])]): (acc, pair) =>
          val (name, urls) = pair
          acc.indexWhere(_._1 == name) match
            case -1 => acc :+ pair
            case i  => acc.updated(i, (name, acc(i)._2 ++ urls))
        .map: (name, urls) =>
          (name, urls.size, longestCommonPrefix(urls))

      if jvmChanges.nonEmpty then
        hasChanges = true
      sb.append(s"### `$osArch`\n\n")
      sb.append("| JVM | Versions added | URL prefix |\n")
      sb.append("|-----|----------------|------------|\n")
      for (jvm, count, prefix) <- jvmChanges do
        sb.append(s"| `$jvm` | $count | `$prefix` |\n")
      sb.append("\n")

    if !hasChanges then
      sb.append("No new JVM versions were added.\n")

    print(sb.toString())
